mutation CREATE_PRODUCT($input: ProductInput) {
  createProduct(input: $input) {
    name,
    price,
    screen {
      panel,
      size,
      resolution
    }
  }
}

# Write your query or mutation here
mutation($id: ID!, $editContent: EditProductInput!) {
  editProductById(id: $id, editContent: $editContent) {
    name
  }
}

 mutation($id: ID!) {
  deleteProductById(id: $id) {
    name,
    memory {
      ram
    }
  }
}

query {
  products {
    id,
    name
  }
}